Add simple CRA example in README
jjranalli/nightwind pull request #24
Opened 2021-06-15 16:11 UTC by Djiit

Fixes #20

2021-06-15 23:29 UTC, jjranalli requested changes
Just had a quick lookup at Helmet docs and it seems the syntax for injecting the script doesn't need `dangerouslySetInnerHTML`. Could you change that line as in the comment? Thanks!

2021-06-15 23:29 UTC, jjranalli commented on README.md
> +      <script dangerouslySetInnerHTML={{ __html: nightwind.init() }} />
Syntax with helmet here should be `<script>{nightwind.init()}</script>`

2021-06-16 08:21 UTC, Djiit commented
Yup, tested locally, works well :)

2021-06-16 11:11 UTC, jjranalli approved these changes

2021-06-16 11:14 UTC, merged